# Generated by Django 4.1.3 on 2022-11-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill", models.CharField(max_length=50, verbose_name="Logros")),
            ],
        ),
        migrations.AddField(
            model_name="usuario",
            name="skill",
            field=models.ManyToManyField(to="usuario.skill"),
        ),
    ]
