# Generated by Django 4.1.3 on 2022-11-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0002_skill_usuario_skill"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skill",
            options={
                "ordering": ["skill"],
                "verbose_name": "Logro",
                "verbose_name_plural": "Logros",
            },
        ),
        migrations.AddField(
            model_name="usuario",
            name="nombre",
            field=models.CharField(default="", max_length=20, verbose_name="Nombre"),
        ),
        migrations.AddField(
            model_name="usuario",
            name="primer_ap",
            field=models.CharField(
                default="", max_length=20, verbose_name="Primer apellido"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="segundo_ap",
            field=models.CharField(
                default="", max_length=20, verbose_name="Segundo apellido"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="cod_gestor",
            field=models.CharField(
                default="", max_length=7, unique=True, verbose_name="Usuario"
            ),
        ),
    ]
