# Generated by Django 4.1.3 on 2022-11-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "usuario",
            "0003_alter_skill_options_usuario_nombre_usuario_primer_ap_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="extension",
            field=models.IntegerField(default=0),
        ),
    ]
