# Generated by Django 4.1.3 on 2022-11-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0004_usuario_email_usuario_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="delegacion",
            field=models.CharField(
                default="", max_length=30, verbose_name="Delegación"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="departamento",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Departamento"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="grupo_titular",
            field=models.CharField(default="", max_length=30, verbose_name="Grupo"),
        ),
        migrations.AddField(
            model_name="usuario",
            name="servicio_titular",
            field=models.CharField(default="", max_length=30, verbose_name="Servicio"),
        ),
    ]
