# Generated by Django 4.1.3 on 2022-11-22 15:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0006_remove_usuario_departamento_usuario_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="comentarios",
            field=ckeditor.fields.RichTextField(default=""),
        ),
    ]
