# Generated by Django 4.1.3 on 2022-11-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0009_remove_usuario_nombre_completo"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="nombre_completo",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="Nombre Completo"
            ),
        ),
    ]
